name: CI

on:
  workflow_dispatch: { }
  push: { }

jobs:

  lint-and-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
      - name: Install dependencies
        run: |
          just bootstrap
      - name: Run lint
        run: |
          just lint
      - name: Run check
        run: |
          just check

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - "18"
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
#      - uses: pdm-project/setup-pdm@main
#        name: Setup PDM
#        with:
#          python-version: ${{ matrix.python-version }} # Version range or exact version of a Python version to use, the same as actions/setup-python
#          architecture: x64    # The target architecture (x86, x64) of the Python interpreter. the same as actions/setup-python
#          enable-pep582: true
#      - name: Install tooling
#        run: pip3 install pytest
      - name: Install deps
        run: just bootstrap
      - name: Run tests
        run: |
          just test

  publish:
    runs-on: ubuntu-latest
    if: >-
      ((github.event_name == 'workflow_dispatch') || (github.event_name == 'push')) &&
      startsWith(github.ref, 'refs/tags/v')
    needs: [ "lint-and-check", "test" ]
    steps:
      - uses: actions/checkout@master
      - uses: extractions/setup-just@v1